https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_conf_send_dependant.json
Start Fetching '5n4pr_conf_send_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_dependant_config.json'
Done  Fetching '5n4pr_conf_send_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_dependant_config.json'
Start Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Done  Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Start Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Done  Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: 
SUCCESS: stop_containers
SUCCESS: reset_nodes_data
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS:




Error executing command: nanomock start && nanomock init_wallets
Error: INFO: Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
INFO:nanomock.internal.utils:Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
SUCCESS: start_containers
SUCCESS:nanomock.internal.utils:start_containers
INFO: WALLET 21EB2BF97FD5888FA26C1CF8220F08B77EA6B352A2AE1582DD1DC5F93E067F97 CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p
INFO: WALLET 64ECD9FB479A8B8DF6DFBEA10937C0301D2F275534C9C4524283E41BE553C99D CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub
INFO: WALLET 99756A1855DEAEF359AEA66423326937B94D0366E18F1A5FC8B4DEEBE9DB0E3F CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6
INFO: WALLET CE68AE9FE5FB5A78A1D47E8744377F63AF9129D2DBBBF0AA54356B48730C5F35 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h
INFO: WALLET 9993E6A707E2A5C55DDBDAF4DDE5B42FAEC0F77D0102469D2FFA2A55E37D9F57 CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8
SUCCESS: ['WALLET 21EB2BF97FD5888FA26C1CF8220F08B77EA6B352A2AE1582DD1DC5F93E067F97 CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p', 'WALLET 64ECD9FB479A8B8DF6DFBEA10937C0301D2F275534C9C4524283E41BE553C99D CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub', 'WALLET 99756A1855DEAEF359AEA66423326937B94D0366E18F1A5FC8B4DEEBE9DB0E3F CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6', 'WALLET CE68AE9FE5FB5A78A1D47E8744377F63AF9129D2DBBBF0AA54356B48730C5F35 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h', 'WALLET 9993E6A707E2A5C55DDBDAF4DDE5B42FAEC0F77D0102469D2FFA2A55E37D9F57 CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8']
.....DEBUG 2 unconfirmed blocks! e.g. 7C6643E0E3D7F1473627A5ED8788FFFAF90A5F10831A333F0C5935C2F3D569CA
.DEBUG 2 unconfirmed blocks! e.g. B9E7FA547B7204D7F43320E865829E23F32416C16BDB27ABD254F4A0025B6A94
.DEBUG 2 unconfirmed blocks! e.g. CEAA1F719C005A9526B78646680B153563C0882F40B595D42452DEB52F7D37CE
.DEBUG 2 unconfirmed blocks! e.g. 4CABB04CDD062B967C6FEAB6A1CC633C5E7B35FECA6221E1B1518A94302DDB60
.DEBUG 2 unconfirmed blocks! e.g. 670C36E0129B512F895AAC3C23623652E0FC44B1E6EBDD889F1FAA3DFA65FA03
.DEBUG 2 unconfirmed blocks! e.g. C905476663A5DC733C63DBF3E88E5656A805E1E9115C5EF9CFCED47841C72C50
.DEBUG 2 unconfirmed blocks! e.g. 316AE731F0F0BA0743856675EF372A3228798DFBF9134D362205D91212007206
.DEBUG 2 unconfirmed blocks! e.g. C3952C84C43C833F130D9F413E984B35C70FC2C8A40ED303BA51A7C762406F6A
.DEBUG 2 unconfirmed blocks! e.g. 9019CD575713B05D5A46FBB18343ED8CF4641A5B91649D0852E2DD049735E309
.DEBUG 2 unconfirmed blocks! e.g. C0814F3C027D8923B5DF4B559778710AEB7EC3BB63FAA37211BA90204454B099
.DEBUG 2 unconfirmed blocks! e.g. 555E0A7DC26E8342F83A2BFF10D85E563063D38344DEFE23C18424C870112A33
.DEBUG 2 unconfirmed blocks! e.g. 14A7CCED5D2AFCCE6418C9F409A6DBFF7FEFD5CEDA9AC4F721EAA5D6A9CBCB7D
.DEBUG 2 unconfirmed blocks! e.g. E5BE3AC30F0AC868B1A72A5149BB59C507DF6A523090CFDF053A0387A5E2DED8
.DEBUG 2 unconfirmed blocks! e.g. 0FB012CD5971258AF5D228D8137209774E3C8BDE07BDE176FEE653379D2A0917
.DEBUG 2 unconfirmed blocks! e.g. BA2CC9DDB0680C3C6093B88F309BC4C83BEBD920D77414EB1B98B60FC3D01157
.DEBUG 2 unconfirmed blocks! e.g. 1B5EB7AA2E1DAFDC03DFE2CFC97D516BAB7AED052BF9B63B24CF7605513D77F5
.DEBUG 2 unconfirmed blocks! e.g. FA06E5953B06CEBEDFC7ABB80E8E941B1D4AEC9F54D4B01EE61E7696431E0268
.DEBUG 2 unconfirmed blocks! e.g. 18A6EC83E1ECF2AB9973C09171EB398AEF10759AAC85E16C4DE3F6D9579E718C
.DEBUG 2 unconfirmed blocks! e.g. 01EBE2DAFCB15083DA1A311A848654AC851EEBD31C05CF359B10F663D1883427
.DEBUG 2 unconfirmed blocks! e.g. E04467CE5E6658400053BF69643B747E3FCD3B97F7865D2630100DCE0A0ED0DC
.DEBUG 2 unconfirmed blocks! e.g. C62A49839947C82807E447C02BAF64D569746AB90F0B9D786C203DFE7D84935E
.DEBUG 2 unconfirmed blocks! e.g. 96BDD85CF47F821ADDE894F4F0ACE22BDBB1787C9A849C79123EE72DC91892C9
.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/threaded_command_mixin.py", line 25, in _execute_command_sequence
    self.command_instance.execute_another_command(command_config)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 35, in publish_create
    asyncio.run(test_case.run())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 120, in run
    await self._generate_and_confirm_block(seed_index)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 110, in _generate_and_confirm_block
    await self.ba_l.assert_blocks_confirmed_wait(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 114, in assert_blocks_confirmed_wait
    confirmed_blocks = await self._blocks_confirmed(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 84, in _blocks_confirmed
    block_info = await self._fetch_block_info(block_hash)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 51, in _fetch_block_info
    return await self.nano_rpc_default.block_info(block_hash,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 472, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 499, in process_payloads
    async with session.post(self.url, json=payloads[0]) as response:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
